apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: homework-sc
  namespace: homework
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain 