apiVersion: v1
kind: Pod
metadata:
  name: homework-server
  namespace: homework
spec:
  containers:
  - name: dir-server
    image: nginx:1.25.5
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8000
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm /homework/index.html"]
    volumeMounts:
    - name: shared-data
      mountPath: /homework
    - name: nginx-config-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  initContainers:
  - name: init-index-downloader
    image: busybox:1.36.1
    command: ['sh', '-c', 'wget -O /init/index.html https://link.hr-link.ru/']
    volumeMounts:
    - mountPath: /init
      name: shared-data
  volumes:
  - name: shared-data
    emptyDir:
      sizeLimit: 500Mi
  - name: nginx-config-volume
    configMap:
      name: nginx-config
  